import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // Template Selection Mode Styles
  selectionContainer: {
    width: 280,
    height: 440,
    backgroundColor: '#1A1A1A',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#333333',
    overflow: 'hidden',
    marginHorizontal: 8,
  },
  selected: {
    borderColor: '#FFD700',
    borderWidth: 3,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  selectionHeader: {
    backgroundColor: '#242424',
    padding: 16,
    paddingBottom: 20,
  },
  accentBar: {
    height: 3,
    backgroundColor: '#FFD700',
    borderRadius: 2,
    marginBottom: 12,
  },
  badge: {
    backgroundColor: '#FFD700',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  badgeText: {
    color: '#1A1A1A',
    fontSize: 12,
    fontWeight: '600',
  },
  selectionContent: {
    flex: 1,
    padding: 16,
  },
  selectionName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  selectionTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFD700',
    marginBottom: 12,
  },
  divider: {
    height: 1,
    backgroundColor: '#333333',
    marginVertical: 12,
  },
  selectionInfoSection: {
    gap: 10,
  },
  selectionInfoItem: {
    marginBottom: 4,
  },
  infoLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: '#999999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 3,
  },
  selectionInfoValue: {
    fontSize: 12,
    color: '#E0E0E0',
    lineHeight: 16,
  },
  footer: {
    height: 6,
    backgroundColor: '#FFD700',
  },

  // Preview Mode Styles
  card: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#1A1A1A',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  headerBackground: {
    height: 100,
    backgroundColor: '#242424',
    borderBottomWidth: 3,
    borderBottomColor: '#FFD700',
  },
  profileSection: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: -40,
    paddingBottom: 20,
    marginTop: -40,
  },
  profileImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#333333',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FFD700',
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#FFD700',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  profileImagePlaceholder: {
    fontSize: 40,
    color: '#666',
  },
  name: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
    textAlign: 'center',
  },
  designation: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFD700',
    marginBottom: 4,
    textAlign: 'center',
  },
  company: {
    fontSize: 13,
    fontWeight: '500',
    color: '#999',
    textAlign: 'center',
  },
  detailsSection: {
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  contactInfo: {
    marginBottom: 20,
  },
  contactItem: {
    flexDirection: 'column',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: '#242424',
    borderRadius: 8,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#FFD700',
  },
  contactValue: {
    fontSize: 13,
    color: '#E0E0E0',
    fontWeight: '500',
    marginTop: 4,
  },
  socialMediaSection: {
    borderTopWidth: 1,
    borderTopColor: '#333333',
    paddingTop: 16,
  },
  socialLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFD700',
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  socialLinksContainer: {
    marginTop: 8,
  },
  socialLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#242424',
    borderRadius: 6,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#FFD700',
  },
  socialIconLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFD700',
    marginRight: 10,
    minWidth: 20,
    textAlign: 'center',
  },
  socialText: {
    fontSize: 13,
    color: '#E0E0E0',
    flex: 1,
  },
});

export default styles;
