import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // Template Selection Mode Styles
  selectionContainer: {
    width: 280,
    height: 440,
    backgroundColor: '#FAFAFA',
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#F0F0F0',
    overflow: 'hidden',
    marginHorizontal: 8,
    padding: 24,
    justifyContent: 'space-between',
  },
  selected: {
    borderColor: '#333333',
    borderWidth: 3,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 8,
  },
  badge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    backgroundColor: '#F0F0F0',
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#666666',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  selectionContent: {
    flex: 1,
    justifyContent: 'space-between',
  },
  spacer: {
    flex: 1,
  },
  selectionName: {
    fontSize: 20,
    fontWeight: '300',
    color: '#1F1F1F',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  selectionTitle: {
    fontSize: 13,
    fontWeight: '400',
    color: '#999999',
    letterSpacing: 0.3,
  },
  selectionContactContainer: {
    gap: 8,
  },
  contact: {
    fontSize: 11,
    color: '#777777',
    lineHeight: 16,
    letterSpacing: 0.2,
  },

  // Preview Mode Styles
  card: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    overflow: 'hidden',
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  profileSection: {
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
    backgroundColor: '#FAFAFA',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  profileImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#F0F0F0',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    marginBottom: 16,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  profileImagePlaceholder: {
    fontSize: 40,
    color: '#999',
  },
  name: {
    fontSize: 20,
    fontWeight: '300',
    color: '#1F1F1F',
    marginBottom: 4,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  designation: {
    fontSize: 13,
    fontWeight: '400',
    color: '#999',
    marginBottom: 4,
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  company: {
    fontSize: 12,
    fontWeight: '400',
    color: '#666',
    textAlign: 'center',
  },
  detailsSection: {
    paddingHorizontal: 20,
    paddingVertical: 20,
  },
  contactInfo: {
    marginBottom: 20,
  },
  contactItem: {
    flexDirection: 'column',
    paddingVertical: 10,
    paddingHorizontal: 0,
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  contactLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  contactValue: {
    fontSize: 12,
    color: '#333',
    fontWeight: '400',
    letterSpacing: 0.2,
  },
  socialMediaSection: {
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    paddingTop: 16,
  },
  socialLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 12,
  },
  socialLinksContainer: {
    marginTop: 8,
  },
  socialLink: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 0,
    marginBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  socialIconLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: '#999',
    marginRight: 8,
    minWidth: 20,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  socialText: {
    fontSize: 12,
    color: '#333',
    flex: 1,
    letterSpacing: 0.2,
  },
});

export default styles;
